#!/bin/sh
#
# Copyright © 2015-2021 the original authors.
#
# Gradle - Build Tool (https://gradle.org/)
#
# This script is generated by `gradle wrapper` and should be committed to VCS.
#

# Determine the path to this script
APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Resolve links - $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`dirname "$PRG"`"/$link"
    fi
done

SAVED="`pwd`"
cd "`dirname \"$PRG\"`/" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_HOME="${APP_HOME%/}"
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine JAVA_HOME if not set
if [ -z "$JAVA_HOME" ]; then
    if command -v java > /dev/null 2>&1; then
        JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
    fi
fi

JAVA="$JAVA_HOME/bin/java"

exec "$JAVA" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
